sudo: false
language: java
jdk:
  - oraclejdk8

script: bin/ci.sh
before_install:
  - mkdir -p $HOME/.local/bin
  - export PATH="$HOME/.local/bin/boot":"$PATH"
  - curl -L https://github.com/boot-clj/boot-bin/releases/download/latest/boot.sh -o $HOME/.local/bin/boot
  - chmod +x $HOME/.local/bin/boot
install: boot show -d

cache:
  directories:
    - $HOME/.local/bin
    - $HOME/.m2
    - $HOME/.boot/cache/bin
    - $HOME/.boot/cache/lib

notifications:
  email:
    on_success: never
    on_failure: change
  slack:
    secure: WJQ1nFJaHsJVQb8hetNYZGR5yDIsUQ0o7kayacw1rdHNz0d6kSUYW4hN2k++tdXbGiCsnJrxGa4jU8mUwCzbkZM9xwNYf8qqw4VhSxfU0/1r59mIQqCdDbAWyFo0MrYdhIRKM//ZrXtzZ0KRyJatsq4qXGdDKB0MRzgVmtnIga8=
