{:chapter-list
 [{:ch-num 1, :name "The Gamer 1",   :url "/the-gamer/1"}
  {:ch-num 2, :name "The Gamer 2",   :url "/the-gamer/2"}
  {:ch-num 3, :name "The Gamer 3",   :url "/the-gamer/3"}
  {:ch-num 4, :name "The Gamer 4",   :url "/the-gamer/4"}
  {:ch-num 5, :name "The Gamer 5",   :url "/the-gamer/5"}
  {:ch-num 6, :name "The Gamer 6",   :url "/the-gamer/6"}
  {:ch-num 7, :name "The Gamer 7",   :url "/the-gamer/7"}
  {:ch-num 8, :name "The Gamer 8",   :url "/the-gamer/8"}
  {:ch-num 9, :name "The Gamer 9",   :url "/the-gamer/9"}
  {:ch-num 10, :name "The Gamer 10", :url "/the-gamer/10"}
  {:ch-num 11, :name "The Gamer 11", :url "/the-gamer/11"}
  {:ch-num 12, :name "The Gamer 12", :url "/the-gamer/12"}
  {:ch-num 13, :name "The Gamer 13", :url "/the-gamer/13"}
  {:ch-num 14, :name "The Gamer 14", :url "/the-gamer/14"}
  {:ch-num 15, :name "The Gamer 15", :url "/the-gamer/15"}
  {:ch-num 16, :name "The Gamer 16", :url "/the-gamer/16"}
  {:ch-num 17, :name "The Gamer 17", :url "/the-gamer/17"}
  {:ch-num 18, :name "The Gamer 18", :url "/the-gamer/18"}
  {:ch-num 19, :name "The Gamer 19", :url "/the-gamer/19"}
  {:ch-num 20, :name "The Gamer 20", :url "/the-gamer/20"}
  {:ch-num 21, :name "The Gamer 21", :url "/the-gamer/21"}
  {:ch-num 22, :name "The Gamer 22", :url "/the-gamer/22"}
  {:ch-num 23, :name "The Gamer 23", :url "/the-gamer/23"}
  {:ch-num 24, :name "The Gamer 24", :url "/the-gamer/24"}
  {:ch-num 25, :name "The Gamer 25", :url "/the-gamer/25"}
  {:ch-num 26, :name "The Gamer 26", :url "/the-gamer/26"}
  {:ch-num 27, :name "The Gamer 27", :url "/the-gamer/27"}
  {:ch-num 28, :name "The Gamer 28", :url "/the-gamer/28"}
  {:ch-num 29, :name "The Gamer 29", :url "/the-gamer/29"}
  {:ch-num 30, :name "The Gamer 30", :url "/the-gamer/30"}
  {:ch-num 31, :name "The Gamer 31", :url "/the-gamer/31"}
  {:ch-num 32, :name "The Gamer 32", :url "/the-gamer/32"}
  {:ch-num 33, :name "The Gamer 33", :url "/the-gamer/33"}
  {:ch-num 34, :name "The Gamer 34", :url "/the-gamer/34"}
  {:ch-num 35, :name "The Gamer 35", :url "/the-gamer/35"}
  {:ch-num 36, :name "The Gamer 36", :url "/the-gamer/36"}
  {:ch-num 37, :name "The Gamer 37", :url "/the-gamer/37"}
  {:ch-num 38, :name "The Gamer 38", :url "/the-gamer/38"}
  {:ch-num 39, :name "The Gamer 39", :url "/the-gamer/39"}
  {:ch-num 40, :name "The Gamer 40", :url "/the-gamer/40"}
  {:ch-num 41, :name "The Gamer 41", :url "/the-gamer/41"}
  {:ch-num 42, :name "The Gamer 42", :url "/the-gamer/42"}
  {:ch-num 43, :name "The Gamer 43", :url "/the-gamer/43"}
  {:ch-num 44, :name "The Gamer 44", :url "/the-gamer/44"}
  {:ch-num 45, :name "The Gamer 45", :url "/the-gamer/45"}
  {:ch-num 46, :name "The Gamer 46", :url "/the-gamer/46"}
  {:ch-num 47, :name "The Gamer 47", :url "/the-gamer/47"}
  {:ch-num 48, :name "The Gamer 48", :url "/the-gamer/48"}
  {:ch-num 49, :name "The Gamer 49", :url "/the-gamer/49"}
  {:ch-num 50, :name "The Gamer 50", :url "/the-gamer/50"}
  {:ch-num 51, :name "The Gamer 51", :url "/the-gamer/51"}
  {:ch-num 52, :name "The Gamer 52", :url "/the-gamer/52"}
  {:ch-num 53, :name "The Gamer 53", :url "/the-gamer/53"}
  {:ch-num 54, :name "The Gamer 54", :url "/the-gamer/54"}
  {:ch-num 55, :name "The Gamer 55", :url "/the-gamer/55"}
  {:ch-num 56, :name "The Gamer 56", :url "/the-gamer/56"}
  {:ch-num 57, :name "The Gamer 57", :url "/the-gamer/57"}
  {:ch-num 58, :name "The Gamer 58", :url "/the-gamer/58"}
  {:ch-num 59, :name "The Gamer 59", :url "/the-gamer/59"}
  {:ch-num 60, :name "The Gamer 60", :url "/the-gamer/60"}
  {:ch-num 61, :name "The Gamer 61", :url "/the-gamer/61"}
  {:ch-num 62, :name "The Gamer 62", :url "/the-gamer/62"}
  {:ch-num 63, :name "The Gamer 63", :url "/the-gamer/63"}
  {:ch-num 64, :name "The Gamer 64", :url "/the-gamer/64"}
  {:ch-num 65, :name "The Gamer 65", :url "/the-gamer/65"}
  {:ch-num 66, :name "The Gamer 66", :url "/the-gamer/66"}
  {:ch-num 67, :name "The Gamer 67", :url "/the-gamer/67"}
  {:ch-num 68, :name "The Gamer 68", :url "/the-gamer/68"}
  {:ch-num 69, :name "The Gamer 69", :url "/the-gamer/69"}
  {:ch-num 70, :name "The Gamer 70", :url "/the-gamer/70"}
  {:ch-num 71, :name "The Gamer 71", :url "/the-gamer/71"}
  {:ch-num 72, :name "The Gamer 72", :url "/the-gamer/72"}
  {:ch-num 73, :name "The Gamer 73", :url "/the-gamer/73"}
  {:ch-num 74, :name "The Gamer 74", :url "/the-gamer/74"}
  {:ch-num 75, :name "The Gamer 75", :url "/the-gamer/75"}
  {:ch-num 76, :name "The Gamer 76", :url "/the-gamer/76"}
  {:ch-num 77, :name "The Gamer 77", :url "/the-gamer/77"}
  {:ch-num 78, :name "The Gamer 78", :url "/the-gamer/78"}
  {:ch-num 79, :name "The Gamer 79", :url "/the-gamer/79"}
  {:ch-num 80, :name "The Gamer 80", :url "/the-gamer/80"}
  {:ch-num 81, :name "The Gamer 81", :url "/the-gamer/81"}
  {:ch-num 82, :name "The Gamer 82", :url "/the-gamer/82"}
  {:ch-num 83, :name "The Gamer 83", :url "/the-gamer/83"}
  {:ch-num 84, :name "The Gamer 84", :url "/the-gamer/84"}
  {:ch-num 85, :name "The Gamer 85", :url "/the-gamer/85"}
  {:ch-num 86, :name "The Gamer 86", :url "/the-gamer/86"}
  {:ch-num 87, :name "The Gamer 87", :url "/the-gamer/87"}
  {:ch-num 88, :name "The Gamer 88", :url "/the-gamer/88"}
  {:ch-num 89, :name "The Gamer 89", :url "/the-gamer/89"}
  {:ch-num 90, :name "The Gamer 90", :url "/the-gamer/90"}
  {:ch-num 91, :name "The Gamer 91", :url "/the-gamer/91"}
  {:ch-num 92, :name "The Gamer 92", :url "/the-gamer/92"}
  {:ch-num 93, :name "The Gamer 93", :url "/the-gamer/93"}
  {:ch-num 94, :name "The Gamer 94", :url "/the-gamer/94"}
  {:ch-num 95, :name "The Gamer 95", :url "/the-gamer/95"}]}
